fgpv-vpgf/contributed-plugins

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/4)

main readme update

---

README.md
my-first-plugin/package-lock.json
my-first-plugin/src/index.ts
thematic-slider/README.md
thematic-slider/compileSass.sh
thematic-slider/package-lock.json
thematic-slider/package.json
thematic-slider/src/index.ts
thematic-slider/src/loader.js
thematic-slider/src/main.scss
thematic-slider/src/samples/thematic-slider-index.html
thematic-slider/src/samples/thematic-slider-loop-config.json
thematic-slider/src/samples/thematic-slider-naked-config.json
thematic-slider/src/samples/thematic-slider-open-config.json
thematic-slider/src/samples/thematic-slider-stack-config.json
thematic-slider/src/slider-controls.ts
thematic-slider/src/slider-panel.ts
thematic-slider/src/template.ts
thematic-slider/tsconfig.json
thematic-slider/webpack.config.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/10)

feat(thematic-slider): Add thematic slider

---

README.md
draw/README.md
my-first-plugin/src/main.scss
range-slider/README.md
range-slider/compileSass.sh
range-slider/package-lock.json
range-slider/package.json
range-slider/src/index.ts
range-slider/src/loader.js
range-slider/src/main.scss
range-slider/src/samples/range-slider-index.html
range-slider/src/samples/slider-esridate-config.json
range-slider/src/samples/slider-esrinumber-config.json
range-slider/src/samples/slider-esrinumber-multilayer-config.json
range-slider/src/samples/slider-realwmsnumber-config.json
range-slider/src/samples/slider-realwmst-config.json
range-slider/src/samples/slider-wmsdate-config.json
range-slider/src/samples/slider-wmsnumber-config.json
range-slider/src/slider-bar.ts
range-slider/src/slider-controls.ts
range-slider/src/template.ts
range-slider/tsconfig.json
range-slider/webpack.config.js
swiper/README.md
swiper/src/index.ts
thematic-slider/README.md
thematic-slider/src/slider-controls.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/11)

feat(range-slider) Add range slider

---

draw/README.md
draw/package.json
draw/src/index.ts
draw/src/samples/draw-config.json
draw/src/toolbar.ts

Closes #9, #13
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/15)

fix(draw): open by default and remove duplicate vertices

---

chart/README.md
chart/src/chart-loader.ts
chart/src/samples/chart-CFS-Month.json
chart/src/samples/chart-CFS-Total.json
chart/src/samples/chart-CFS-Year.json
chart/src/samples/chart-index.html

Closes #16
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/21)

samples(chart): Add samples for CFS data

---

chart/README.md
chart/package-lock.json
chart/package.json
chart/src/chart-bar.ts
chart/src/chart-loader.ts
chart/src/index.ts
chart/src/main.scss
chart/src/samples/chart-CFS-Month.json
chart/src/samples/chart-CFS-Total.json
chart/src/samples/chart-CFS-Year.json
chart/src/samples/chart-bar-config.json
chart/src/samples/chart-barmulti-config.json
chart/src/samples/chart-doughnut-config.json
chart/src/samples/chart-index.html
chart/src/samples/chart-linecombine-date-config.json
chart/src/samples/chart-linecombine-number-config.json
chart/src/template.ts
chart/tsconfig.json
draw/src/toolbar.ts

Closes #20
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/22)

feat(chart): Add a slider to refine chart by years selected by user

---

range-slider/README.md
range-slider/src/index.ts
range-slider/src/samples/slider-esridate-config.json
range-slider/src/samples/slider-esrinumber-config.json
range-slider/src/samples/slider-esrinumber-multilayer-config.json
range-slider/src/samples/slider-realwmsnumber-config.json
range-slider/src/samples/slider-realwmst-config.json
range-slider/src/samples/slider-wmsdate-config.json
range-slider/src/samples/slider-wmsnumber-config.json

Closes #8
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/25)

feat(rangeSlider): Add a parameter to have it open or close by default

---

buildAll.sh

Closes #26
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/27)

feat(core): Add a build all plugins process

---

range-slider/src/index.ts
range-slider/src/samples/range-slider-index.html
range-slider/src/samples/slider-default-config.json

Closes #32
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/34)

fix(range): Make it open or closed by default

---

chart/README.md
chart/src/chart-bar.ts
chart/src/chart-loader.ts
chart/src/samples/chart-CFS-Month.json
chart/src/samples/chart-CFS-Total.json
chart/src/samples/chart-CFS-Year.json

Closes #28, #29
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/35)

fix(chart): Improve doc, update samples and fix a bug with slider date

---

chart/src/chart-line.ts
chart/src/chart-loader.ts
chart/src/index.ts
chart/src/main.scss
chart/src/samples/chart-CFS-Month.json
chart/src/samples/chart-CFS-Total.json
chart/src/samples/chart-CFS-Year.json
chart/src/samples/chart-bar-config.json
chart/src/samples/chart-barmulti-config.json
chart/src/samples/chart-doughnut-config.json
chart/src/samples/chart-linecombine-date-config.json
chart/src/samples/chart-linecombine-number-config.json
chart/src/template.ts

Closes #38
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/42)

feat(chart): Add a y value slider to line chart

---

draw/src/panel-manager.ts
draw/src/toolbar.ts

Closes #44
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/47)

fix(draw) Add WCAG message when using the plugin with a keyboard

---

range-slider/README.md
range-slider/package-lock.json
range-slider/package.json
range-slider/src/index.ts
range-slider/src/samples/slider-esrinumber-config.json
range-slider/src/slider-bar.ts
range-slider/src/slider-controls.ts
range-slider/src/template.ts

Closes #48, #49
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/50)

fix(range): Apply delay on play and make GIF animated

---

range-slider/README.md
range-slider/src/index.ts
range-slider/src/main.scss
range-slider/src/samples/range-slider-index.html
range-slider/src/samples/slider-default-config.json
range-slider/src/samples/slider-esridate-config.json
range-slider/src/samples/slider-esrinumber-config.json
range-slider/src/samples/slider-esrinumber-multilayer-config.json
range-slider/src/samples/slider-realwmsnumber-config.json
range-slider/src/samples/slider-realwmst-config.json
range-slider/src/samples/slider-wmsdate-config.json
range-slider/src/samples/slider-wmsnumber-config.json
range-slider/src/slider-bar.ts
range-slider/src/slider-controls.ts
range-slider/src/slider-manager.ts
range-slider/src/template.ts

Closes #60
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/66)

feat(range): Add description to slider (layers, fields, units and text)

---

chart/package-lock.json
chart/package.json
chart/src/samples/chart-index.html
chart/webpack.config.js
draw/package-lock.json
draw/package.json
draw/src/samples/draw-index.html
draw/webpack.config.js
my-first-plugin/package-lock.json
my-first-plugin/package.json
my-first-plugin/src/samples/my-first-plugin-index.html
my-first-plugin/webpack.config.js
range-slider/package-lock.json
range-slider/package.json
range-slider/webpack.config.js
swiper/package-lock.json
swiper/package.json
swiper/src/samples/swiper-index.html
swiper/webpack.config.js
thematic-slider/package-lock.json
thematic-slider/package.json
thematic-slider/src/samples/thematic-slider-index.html
thematic-slider/webpack.config.js

Closes #62, #87
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/88)

chore(dependencies): Update dependecies and solve an sample index issue

---

thematic-slider/README.md
thematic-slider/src/index.ts
thematic-slider/src/main.scss
thematic-slider/src/samples/thematic-slider-custom-legend-config.json
thematic-slider/src/samples/thematic-slider-index.html
thematic-slider/src/samples/thematic-slider-loop-config.json
thematic-slider/src/samples/thematic-slider-naked-config.json
thematic-slider/src/samples/thematic-slider-osdp1-config.json
thematic-slider/src/samples/thematic-slider-osdp2-config.json
thematic-slider/src/samples/thematic-slider-osdp3-config.json
thematic-slider/src/samples/thematic-slider-stack-config.json
thematic-slider/src/samples/thematic-slider-wms-config.json
thematic-slider/src/slider-controls.ts
thematic-slider/src/slider-panel.ts
thematic-slider/src/template.ts

Closes #85
Take a look at to see it in action
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90)

feat(thematic): Add details panel and legend

---

thematic-slider/src/samples/thematic-slider-wms-config.json
thematic-slider/src/slider-panel.ts

Closes #96
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/97)

fix(thematic): Fix legend update and WMS sample

---

chart/package-lock.json
chart/package.json
chart/webpack.config.js
draw/package-lock.json
draw/package.json
draw/webpack.config.js
my-first-plugin/package-lock.json
my-first-plugin/package.json
my-first-plugin/webpack.config.js
range-slider/package-lock.json
range-slider/package.json
range-slider/webpack.config.js
swiper/package-lock.json
swiper/package.json
swiper/webpack.config.js
thematic-slider/package-lock.json
thematic-slider/package.json
thematic-slider/webpack.config.js

Closes #117
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/119)

fix(core) Fix security dependencies issues

---

draw/src/samples/draw-index.html
draw/src/toolbar.ts

Closes 108
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/120)

fix(draw): Duplicate point on edit

---

range-slider/src/index.ts
range-slider/src/slider-bar.ts

Closes #124
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/129)

fix(range): Set default step for keyboard

---

draw/package-lock.json
draw/package.json
package-lock.json
range-slider/package-lock.json
range-slider/package.json
swiper/package-lock.json
swiper/package.json
thematic-slider/package-lock.json
thematic-slider/package.json

closes(123)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/138)

fix(123): remove unused dependencies from package.json

---

chart/README.md

closes(137)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/139)

fix(127): fix chart readme.md

---

chart/package-lock.json
chart/package.json
chart/webpack.config.js
draw/package-lock.json
draw/package.json
draw/webpack.config.js
my-first-plugin/package-lock.json
my-first-plugin/package.json
my-first-plugin/webpack.config.js
range-slider/package-lock.json
range-slider/package.json
range-slider/webpack.config.js
swiper/package-lock.json
swiper/package.json
swiper/webpack.config.js
thematic-slider/package-lock.json
thematic-slider/package.json
thematic-slider/webpack.config.js

Closes #134
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/149)

core(build): Add version to build file

---

README.md

closes(153)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/170)

fix(153): add link to FGP guideline in Readme

---

chart/webpack.config.js
range-slider/src/index.ts
range-slider/src/slider-manager.ts
range-slider/webpack.config.js

Closes #166
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/173)

fix(range-slider): Show menu button only when there is a slider

---

range-slider/src/slider-bar.ts
range-slider/src/slider-manager.ts

Closes #171
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/176)

fix(range-slider): Wrong slider start date

---

chart/package-lock.json
chart/package.json
chart/webpack.config.js
draw/package-lock.json
draw/package.json
draw/webpack.config.js
range-slider/package-lock.json
range-slider/package.json
range-slider/webpack.config.js
swiper/package-lock.json
swiper/package.json
swiper/webpack.config.js
thematic-slider/package-lock.json
thematic-slider/package.json
thematic-slider/webpack.config.js

Closes #168
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/184)

fix(core): Fix Webpack issues, add time stamp to js file

---

range-slider/README.md
range-slider/package.json
range-slider/src/index.ts
range-slider/src/samples/slider-flood-config.json
range-slider/src/samples/slider-osdp2-config.json
range-slider/src/samples/slider-realwmst-config.json
range-slider/src/slider-manager.ts

Close #189
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/190)

fix(range-slider): Encode uri and config modifications

---

range-slider/README.md
range-slider/package-lock.json
range-slider/package.json
range-slider/src/main.scss
range-slider/src/samples/slider-flood-config.json
range-slider/src/slider-bar.ts
range-slider/src/slider-manager.ts

Closes #193, #194, #195, #196
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/198)

fix(range-slider): Readme, Flood sample, interval setting and padding

---

swiper/src/index.ts
swiper/src/main.scss
swiper/src/samples/swiper-horizontal-config.json
swiper/src/samples/swiper-index.html

closes(177)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/191)

fix(177): add horizontal swiper

---

chart/package-lock.json
chart/src/chart-bar.ts
chart/src/chart-line.ts
chart/src/chart-loader.ts
chart/src/index.ts
chart/src/main.scss
chart/src/template.ts
draw/src/index.ts
draw/src/main.scss
draw/src/panel-manager.ts
draw/src/template.ts
draw/src/toolbar.ts
draw/webpack.config.js
my-first-plugin/webpack.config.js
range-slider/src/main.scss
swiper/webpack.config.js
thematic-slider/webpack.config.js

Closes #147
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/199)

fix(wcag) WCAG issue for many plugins

---

chart/package-lock.json
chart/package.json
draw/package-lock.json
draw/package.json
my-first-plugin/package-lock.json
my-first-plugin/package.json
package-lock.json
range-slider/package-lock.json
range-slider/package.json
range-slider/src/main.scss
swiper/package-lock.json
swiper/package.json
thematic-slider/package-lock.json
thematic-slider/package.json

Closes #197
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/222)

fix(dep): Fix dependencies security issues

---

range-slider/src/index.ts
range-slider/src/main.scss
range-slider/src/slider-bar.ts
range-slider/src/slider-manager.ts

Closes #224, #225, #226
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/227)

fix(range-slider): Remove def query on close and style issues

---

range-slider/src/template.ts

Closes #230
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/237)

fix(range-slider): Description icon confusing, set it as the others

---

range-slider/src/main.scss

Closes #238
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/242)

fix(range-slider): Style issue when minimize and for small screen

---

range-slider/README.md
range-slider/src/index.ts
range-slider/src/main.scss
range-slider/src/samples/slider-dual-static-config.json
range-slider/src/slider-bar.ts
range-slider/src/slider-controls.ts
range-slider/src/template.ts

Closes #239
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/247)

fix(range-slider): Lock handle with reverse and loop

---

README.md
buildAll.sh
chart/package-lock.json
draw/package-lock.json
range-slider/package-lock.json
swiper/package-lock.json
thematic-slider/package-lock.json

CLoses #248
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/249)

fix(dependecies): Update automatic build to fix dependancies as well

---

buildAll.sh

Closes #256
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/257)

fix(dep): Fix dependabot

---

chart/README.md
chart/src/chart-loader.ts
chart/src/chart-parser.ts
chart/src/samples/chart-index.html

Closes #261, #186, #137
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/262)

fix(chart): Order by date field and documentation

---

chart/src/chart-loader.ts
chart/src/chart-parser.ts

Closes #130
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/263)

fix(chart): made it work with multiple data field inside one layer

---

range-slider/src/index.ts
range-slider/src/samples/range-slider-index.html
range-slider/src/samples/slider-esritimeaware-config-c.json
range-slider/src/slider-manager.ts

Closes #268
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/270)

fix(range-slider): Auto configure image server

---

range-slider/src/index.ts
range-slider/src/slider-bar.ts
range-slider/src/slider-manager.ts

Closes #271
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/273)

fix(range-slider): Auto load WMS (CRS, proxy and bad format)

---

chart/src/chart-parser.ts

Closes #274
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/275)

fix(chart): Manage apostrphe in field value when we query attributes

---

chart/src/chart-parser.ts

Closes #276
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/277)

fix(chart): remove double apostrophe from selector

---

chart/src/chart-controls.ts
chart/src/details-manager.ts
range-slider/src/slider-controls.ts
thematic-slider/src/index.ts

Closes #282
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/284)

fix(RAMP): Vis retro compatibility with ramp 3.3.3

---

range-slider/src/slider-manager.ts

Closes #287
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/288)

fix(range-slider): Do not start slider if layer has no type

---

range-slider/src/index.ts
range-slider/src/slider-bar.ts
range-slider/src/slider-manager.ts

Closes #290
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/303)

feat(range-slider): Remove slider when layers are removed

---

range-slider/src/slider-manager.ts

Closes #291
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/305)

fix(range-slider): Add field name use to parse for no config added layer

---

range-slider/src/slider-bar.ts
range-slider/src/slider-manager.ts
swiper/README.md

closes(#265)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/294)

fix(265): stop range slider from running when deselected

---

draw/src/panel-manager.ts

Closes #314
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/321)

fix(draw): Solve bug with delete from extent with Keyboard

---

chart/package-lock.json
draw/package-lock.json
my-first-plugin/package-lock.json
swiper/package-lock.json
thematic-slider/package-lock.json

Closes #310, #309, #311, #312, #313, #314, #315, #316, #317, #318, #319, #320
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/324)

fix(deps): Fix dependencies issues

---

range-slider/src/index.ts

closes(333)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/337)

fix(333): correct spelling Unités translations

---

thematic-slider/src/slider-panel.ts

closes(333)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/336)

fix(333) permits display of panel over layer panel

---

chart/src/chart-line.ts
chart/src/chart-loader.ts
chart/src/main.scss
chart/src/template.ts

Small changes for bug 328. There are changes till now. 
Right side changes for more spaces still there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/340)

changes for bug 328

---

chart/src/chart-loader.ts
chart/src/chart-pie.ts
chart/src/main.scss
chart/src/samples/Airborne_radioactivity_linechart_en.json
chart/src/samples/chart-doughnut-new-config.json
chart/src/samples/chart-index.html
chart/src/samples/geoJSON/doughnutChart_NewJsonFormat.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/351)

fix(chart): Use multiple fields Closes #83

---

chart/src/index.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/352)

fix(chart): Remove extra s in French  Closes #343

---

chart/src/chart-controls.ts
chart/src/chart-line.ts
chart/src/chart-parser.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/378)

fix(chart): Make color consistent closes #364

---

chart/src/chart-controls.ts
chart/src/chart-parser.ts
chart/src/main.scss

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/380)

fix(chart): closes #379 #359 and move control left

---

chart/src/chart-controls.ts
chart/src/chart-line.ts
chart/src/chart-loader.ts
chart/src/chart-parser.ts
chart/src/common.ts
chart/src/samples/chart-index.html
chart/src/samples/fpsn_chart_en.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/384)

fix(chart): closes #381

---

chart/src/chart-controls.ts
chart/src/chart-loader.ts
chart/src/index.ts
chart/src/main.scss
chart/src/samples/chart-index.html
chart/src/samples/chart-viewonmap-config.json
chart/src/samples/chart-vom-index.html
chart/src/template.ts

Closes #392
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/408)

feat(chart): add view on map

---

range-slider/src/samples/range-slider-index.html
range-slider/src/slider-manager.ts

Closes #407
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/412)

fix(range-slider): remove layer always destroy slider

---

range-slider/src/samples/range-slider-index.html
range-slider/src/samples/slider-empty-config.json
range-slider/src/samples/slider-flood-config.json
range-slider/src/samples/slider-no-config.json
range-slider/src/slider-bar.ts
range-slider/src/slider-manager.ts

Closes #411
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/418)

fix(range-slider): bug when pre config range introduce by latest PR

---

chart/src/index.ts
chart/tsconfig.json

Closes #416
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/422)

fix(chart): Use new GeoCore who parse better the JSON

---

chart/src/chart-loader.ts
chart/src/chart-parser.ts
chart/src/samples/chart-index.html
chart/src/samples/v6-1_line_date_chart.json
chart/src/samples/v6-1_line_linear_chart.json

closes(356)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/436)

fix(356) add  dates in YYYY format

---

package-lock.json
swiper/package-lock.json
swiper/package.json
swiper/src/index.ts
swiper/src/main.scss
swiper/src/samples/swiper-index.html
swiper/src/samples/swiper-osdp3-config.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/472)

fix(swiper): Bas class restric moving swiper
